### ISSUE TITLE
Plugin can't be installed via docpad install command

### ISSUE THREAD

**Issue by Delapouite** [Hypercubed/docpad-plugin-raw#1]
Hello

$> docpad install raw fails

$> npm install docpad-plugin-raw works but then the plugin is considered incompatible because docpad requires that it has a major version number >= 2.

Solution : bump the package.json version to 2.0.0

Thanks

**Comment by Hypercubed** [comment]
I just started seeing this error the other day.  I wasn't sure what to do.  I've bumped the version number to 2.x.  Thanks.
