### ISSUE TITLE
Out folder config for target

### ISSUE THREAD

**Issue by dimitarkolev** [Hypercubed/docpad-plugin-raw#10]
I saw that right now you can configure multiple source location not only /src/raw and different copy methods. It will be great if you can define out location as well, from what i understood you can only configure src.

**Comment by Hypercubed** [comment]
Shouldn't out be defined by the docpad config?  If you think this is needed can you create an issue here: https://github.com/docpad/docpad-plugin-raw/issues .  Thanks.
