### ISSUE TITLE
Make it an official plugin

### ISSUE THREAD

**Issue by balupton** [Hypercubed/docpad-plugin-raw#11]
As discussed in another issue, we've now made this an official plugin here: https://github.com/docpad/docpad-plugin-raw

@Hypercubed can you run:

```
npm owner add balupton docpad-plugin-raw
npm owner add robloach docpad-plugin-raw
```

To give both myself and @RobLoach the ability to publish new npm versions to this plugin, and that will complete the migration.

**Comment by Hypercubed** [comment]
Done.
