### ISSUE TITLE
Command does not work on OSX - Needs Rsync

### ISSUE THREAD

**Issue by autoferrit** [Hypercubed/docpad-plugin-raw#2]
In the Readme, you describe this block of code:

``` coffeescript
# ...
plugins:
    raw:
        commands:
            raw: ['cp', '-Rnl', 'src/raw/*', 'out/' ]
            app: ['cp', '-Rn', 'src/app/*', 'out/' ]
# ...
```

and then mention

```
['cp', '-Rnl'... will create hard links on unix-like systems.
```

but the lowercase 'l' is not a valid option on a mac. the symlink option. So on a mac, I tried this

``` coffeescript
# ...
plugins:
    raw:
        commands:
            raw: ['cp', '-Rn', 'src/raw/*', 'out/' ]
# ...
```

but now, the '*' asterisk causes a problem. So i tried it with just an ending slash. just `src/raw/` but it still did not work for me. It didnt give an error, but it did not copy all the files completely. So i tried using `rsync`

``` coffeescript
plugins:
  raw:
    commands:
      # rsync
      # -r recursive
      # -u skip file if the destination file is newer
      # -l copy any links over as well
      raw  : ['rsync', '-rul', 'src/raw/', 'out/' ]
```

which then worked flawlessly. thanks for the help from @balupton. rsync was already installed on my system so it seems like it is available for any mac user

Apple Docs: https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/rsync.1.html

**Comment by Hypercubed** [comment]
Thanks for the report.  I've added this to the readme as an example.
