### ISSUE TITLE
Let's get this as an official plugin

### ISSUE THREAD

**Issue by balupton** [Hypercubed/docpad-plugin-raw#3]
Can you transfer it to the `docpad` organisation and I'll give you write access again? 

Can you also run: `npm owner add balupton docpad-plugin-raw`

Benefits of this is that the rest of the extras team will be able to maintain the plugin, plus it will get tested with each major and minor docpad release.

**Comment by Hypercubed** [comment]
I can't seam to be able to transfer without admin rights to docpad organisation. I added you as a owner in npm.

**Comment by balupton** [comment]
Try now.

**Comment by Hypercubed** [comment]
I still get the message "You don't have admin rights to docpad".

**Comment by RobLoach** [comment]
https://github.com/Hypercubed/docpad-plugin-raw/issues/11 :lock:
