### ISSUE TITLE
cp command

### ISSUE THREAD

**Issue by stongo** [Hypercubed/docpad-plugin-raw#4]
This cp command will work everywhere. Please update README.md with this. All cp commands in readme fail on Heroku, as well, and Heroku doesn't support rsync. This command also works on macs.

```
        raw:
            commands:
                raw: ['cp', '-Rn', 'src/raw/', 'out/']
```

**Comment by stongo** [comment]
for clarity: the "*" is unnecessary in the cp command currently in README.md

**Comment by stongo** [comment]
nix that, doesn't work on heroku, just mac :(

**Comment by RobLoach** [comment]
Yeah, the `raw` plugin isn't working at all for me (Linux). Perhaps we should switch to using something like [ncp](http://github.com/AvianFlu/ncp/) rather than the custom OS commands.

Ah, you're all over it: https://github.com/Hypercubed/docpad-plugin-raw/pull/6 :+1:

**Comment by RobLoach** [comment]
Now that ncp is in, I suppose this doesn't apply anymore.
